version: '3'
services:
  zookeeper:
    hostname: zookeeper
    image: zookeeper
  kafka:
    hostname: kafka
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
    ports:
      - "9092"
  # producer:
  #   # depends_on:
  #   #   - zookeeper
  #   #   - kafka
  #   image: java:8-jdk-alpine
  #   volumes:
  #     - ./vertex-producer:/vertex-producer
  #   # ports:
  #   #   - "8080:8080"
  #   entrypoint: 
  #     java -jar -Dspring.profiles.active=docker vertex-producer/target/vertx-kafka-producer-0.0.1-SNAPSHOT.jar
  # consumer:
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   image: java:8-jdk-alpine
  #   volumes:
  #     - ./spring-kafka:/spring-kafka
  #   entrypoint: 
  #     java -jar -Dspring.profiles.active=docker spring-kafka/target/spring-kafka-consumer-0.0.1-SNAPSHOT.jar
